# Generated by Django 5.0.1 on 2024-01-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
